services:
  lint:
    image: node:22.14.0-alpine3.21
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: |-
      sh -ceuo pipefail '
        apk add shadow
        usermod -u $HOST_UID node
        su node -c "$$@"'
    command: sh -c 'npm i --no-save eslint && ./node_modules/.bin/eslint --color .'

  test: &test
    image: node:16.15.1-alpine3.16
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: |-
      sh -ceuo pipefail '
        apk add shadow
        usermod -u $HOST_UID node
        su node -c "$$@"'
    command: sh -c 'npm i && npm test'

  watch:
    <<: *test
    command: sh -c 'npm i && npm run watch'

  test-db:
    image: mysql:8.3.0
    stop_signal: SIGKILL
    logging:
      options:
        max-size: 10k # Keep down the noise
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    healthcheck:
      test: '/usr/bin/mysql -D test -u root --execute "SELECT 1"'
      interval: 1s
      timeout: 1s
      retries: 20
