version: '2'

services:
  test: &test
    image: node:16.15.1-alpine
    depends_on:
      test-db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: |-
      sh -ceuo pipefail '
        apk add shadow
        usermod -u $HOST_UID node
        su node -c "$$@"'
    command: sh -c 'npm i && npm run lint-and-test'

  watch:
    <<: *test
    command: sh -c 'npm i && npm run watch'

  test-db:
    image: mysql:5.7
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: '/usr/bin/mysql -D test -u root --execute "SELECT 1"'
      interval: 1s
      timeout: 1s
      retries: 20